# Generated by Django 6.0.2 on 2026-04-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_created_by_alter_membership_club_and_more'),
        ('users', '0003_alter_user_blood_group_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_admins', to='clubs.club'),
        ),
    ]
