# Generated by Django 6.0.2 on 2026-02-17 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registration'),
        ),
    ]
