# Generated by Django 6.0.2 on 2026-04-05 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('registrations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='scanned_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrations.registration'),
        ),
    ]
